[[agents]]
id = "agent1"
name = "HoloTester1"
public_address = "HcSCJdgKMXN47rh9vsfmHuo5VRRt9v3poRdNy84TV8Z4qcqhgC6zTeDAT3durna"
key_file = "./temp-key.key"


[[dnas]]
id = "dna"
file = "./dist/holochain_graphql_starter_kit.dna.json"


[[instances]]
id = "gql-example"
dna = "dna"
agent = "agent1"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "memory"


[[interfaces]]
id = "http-interface"
[interfaces.driver]
type = "http"
port = 3001
[[interfaces.instances]]
id = "gql-example"

#===================================================================
